from io import BytesIO
from datetime import date
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, cm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, PageBreak, KeepTogether
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT, TA_JUSTIFY

# ── Colour palette ────────────────────────────────────────────────────────────
DARK_NAVY   = colors.HexColor("#0f2044")
MID_NAVY    = colors.HexColor("#1a3a6b")
ACCENT_BLUE = colors.HexColor("#2563eb")
TEXT_DARK   = colors.HexColor("#1e293b")
TEXT_MID    = colors.HexColor("#475569")
TEXT_LIGHT  = colors.HexColor("#94a3b8")
ROW_ALT     = colors.HexColor("#f1f5f9")
ROW_HEAD    = colors.HexColor("#e0eaf8")
WHITE       = colors.white
PAGE_W, PAGE_H = A4


def _styles():
    base = getSampleStyleSheet()

    cover_title = ParagraphStyle(
        "CoverTitle", parent=base["Normal"],
        fontName="Helvetica-Bold", fontSize=24,
        textColor=WHITE, alignment=TA_CENTER,
        spaceAfter=10, leading=30,
    )
    cover_sub = ParagraphStyle(
        "CoverSub", parent=base["Normal"],
        fontName="Helvetica", fontSize=11,
        textColor=colors.HexColor("#93c5fd"),
        alignment=TA_CENTER, spaceAfter=6,
    )
    cover_meta = ParagraphStyle(
        "CoverMeta", parent=base["Normal"],
        fontName="Helvetica", fontSize=9,
        textColor=colors.HexColor("#cbd5e1"),
        alignment=TA_CENTER, spaceAfter=5,
    )
    h1 = ParagraphStyle(
        "H1", parent=base["Normal"],
        fontName="Helvetica-Bold", fontSize=13,
        textColor=DARK_NAVY, spaceBefore=4,
        spaceAfter=6, leading=18,
    )
    h2 = ParagraphStyle(
        "H2", parent=base["Normal"],
        fontName="Helvetica-Bold", fontSize=10,
        textColor=MID_NAVY, spaceBefore=14,
        spaceAfter=4,
    )
    body = ParagraphStyle(
        "Body", parent=base["Normal"],
        fontName="Helvetica", fontSize=9.5,
        textColor=TEXT_DARK, leading=15,
        spaceAfter=6, alignment=TA_JUSTIFY,
    )
    caption = ParagraphStyle(
        "Caption", parent=base["Normal"],
        fontName="Helvetica-Oblique", fontSize=8,
        textColor=TEXT_MID, spaceAfter=4,
        alignment=TA_CENTER,
    )
    label = ParagraphStyle(
        "Label", parent=base["Normal"],
        fontName="Helvetica-Bold", fontSize=7.5,
        textColor=ACCENT_BLUE, spaceAfter=2,
        letterSpacing=1.2,
    )
    return cover_title, cover_sub, cover_meta, h1, h2, body, caption, label


def _header_footer(canvas, doc):
    canvas.saveState()
    w, h = A4

    # ── Header bar (skip cover page) ──────────────────────────────────────────
    if doc.page > 1:
        canvas.setFillColor(DARK_NAVY)
        canvas.rect(0, h - 0.55 * inch, w, 0.55 * inch, fill=1, stroke=0)

        canvas.setFont("Helvetica-Bold", 8)
        canvas.setFillColor(WHITE)
        canvas.drawString(0.75 * inch, h - 0.35 * inch, "CLINICAL STUDY REPORT")

        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(colors.HexColor("#93c5fd"))
        canvas.drawRightString(w - 0.75 * inch, h - 0.35 * inch, "CONFIDENTIAL")

        # thin accent line under header
        canvas.setStrokeColor(ACCENT_BLUE)
        canvas.setLineWidth(1.5)
        canvas.line(0, h - 0.57 * inch, w, h - 0.57 * inch)

    # ── Footer ────────────────────────────────────────────────────────────────
    canvas.setStrokeColor(colors.HexColor("#cbd5e1"))
    canvas.setLineWidth(0.5)
    canvas.line(0.75 * inch, 0.65 * inch, w - 0.75 * inch, 0.65 * inch)

    canvas.setFont("Helvetica", 7.5)
    canvas.setFillColor(TEXT_LIGHT)
    canvas.drawString(
        0.75 * inch, 0.45 * inch,
        "Generated by TrialDocAI  ·  Not for regulatory submission without medical writer review"
    )
    canvas.drawRightString(
        w - 0.75 * inch, 0.45 * inch,
        f"Page {doc.page}"
    )
    canvas.restoreState()


def _cover_page(story, structured_data, cover_title, cover_sub, cover_meta):
    """Full-page dark cover with study summary."""

    best_tx  = structured_data.get("best_treatment", "—")
    conf     = structured_data.get("confidence_score", "—")
    warning  = structured_data.get("warning", "—")
    conclusion = structured_data.get("conclusion", "—").upper()
    today    = date.today().strftime("%B %d, %Y")

    # Dark cover background via a full-page table
    cover_content = [
        [Paragraph("CLINICAL STUDY REPORT", cover_title)],
        [Spacer(1, 6)],
        [Paragraph("Prepared by TrialDocAI  ·  Powered by Groq LLaMA 3.3 70B", cover_sub)],
        [Spacer(1, 30)],
        [Paragraph(f"Date: {today}", cover_meta)],
        [Paragraph("Sponsor: Demo Sponsor Inc.", cover_meta)],
        [Paragraph("Document Status: DRAFT — FOR REVIEW", cover_meta)],
        [Spacer(1, 40)],
    ]

    cover_table = Table(cover_content, colWidths=[PAGE_W])
    cover_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), DARK_NAVY),
        ("TOPPADDING",    (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING",   (0, 0), (-1, -1), 0),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 0),
    ]))
    story.append(cover_table)

    # ── Key metrics summary table on cover ────────────────────────────────────
    summary_label_style = ParagraphStyle(
        "SumLabel", fontName="Helvetica-Bold", fontSize=7.5,
        textColor=TEXT_LIGHT, alignment=TA_CENTER, leading=10,
    )
    summary_value_style = ParagraphStyle(
        "SumValue", fontName="Helvetica-Bold", fontSize=13,
        textColor=WHITE, alignment=TA_CENTER, leading=16,
    )

    metrics = Table(
        [[
            Paragraph("BEST TREATMENT", summary_label_style),
            Paragraph("CONCLUSION",     summary_label_style),
            Paragraph("EFFECT",         summary_label_style),
            Paragraph("CONFIDENCE",     summary_label_style),
        ],[
            Paragraph(str(best_tx),    summary_value_style),
            Paragraph(str(conclusion), summary_value_style),
            Paragraph(str(warning),    summary_value_style),
            Paragraph(str(conf),       summary_value_style),
        ]],
        colWidths=[PAGE_W / 4] * 4,
    )
    metrics.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), MID_NAVY),
        ("TOPPADDING",    (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("LEFTPADDING",   (0, 0), (-1, -1), 8),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 8),
        ("LINEAFTER",     (0, 0), (2, -1), 0.5, colors.HexColor("#2563eb")),
        ("LINEBELOW",     (0, 0), (-1, 0), 0.5, colors.HexColor("#2563eb")),
    ]))
    story.append(metrics)
    story.append(PageBreak())


def _results_table(story, structured_data, h2, caption):
    """Styled primary endpoint results table."""
    results = structured_data.get("results", [])
    if not results:
        return

    story.append(Paragraph("Table 1. Primary Endpoint Results — Blood Pressure Reduction (mmHg)", h2))

    tbl_data = [["Treatment Group", "N", "Mean Reduction (mmHg)", "Std Dev"]]
    for r in results:
        tbl_data.append([
            r["treatment"],
            str(r["sample_size"]),
            str(r["mean"]),
            str(r["std_dev"]),
        ])

    col_w = [2.5*inch, 0.9*inch, 2.2*inch, 1.1*inch]
    t = Table(tbl_data, colWidths=col_w, repeatRows=1)
    t.setStyle(TableStyle([
        # Header
        ("BACKGROUND",    (0, 0), (-1, 0), DARK_NAVY),
        ("TEXTCOLOR",     (0, 0), (-1, 0), WHITE),
        ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, 0), 9),
        ("ALIGN",         (0, 0), (-1, 0), "CENTER"),
        ("TOPPADDING",    (0, 0), (-1, 0), 8),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 8),
        # Data rows
        ("FONTNAME",      (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE",      (0, 1), (-1, -1), 9),
        ("TEXTCOLOR",     (0, 1), (-1, -1), TEXT_DARK),
        ("ALIGN",         (1, 1), (-1, -1), "CENTER"),
        ("ALIGN",         (0, 1), (0, -1), "LEFT"),
        ("TOPPADDING",    (0, 1), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 1), (-1, -1), 7),
        ("ROWBACKGROUNDS",(0, 1), (-1, -1), [WHITE, ROW_ALT]),
        # Borders
        ("LINEBELOW",     (0, 0), (-1, 0), 1.5, ACCENT_BLUE),
        ("LINEBELOW",     (0, 1), (-1, -2), 0.3, colors.HexColor("#e2e8f0")),
        ("LINEBELOW",     (0, -1), (-1, -1), 1, DARK_NAVY),
        ("BOX",           (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
        ("LEFTPADDING",   (0, 0), (0, -1), 10),
    ]))
    story.append(t)
    story.append(Paragraph("Note: Values represent mean change from baseline ± standard deviation.", caption))
    story.append(Spacer(1, 10))


def _pairwise_table(story, structured_data, h2, caption):
    """Styled pairwise statistics table."""
    pairwise = structured_data.get("pairwise_stats", [])
    if not pairwise:
        return

    story.append(Paragraph("Table 2. Pairwise Statistical Comparisons vs Placebo (Welch's t-test)", h2))

    pw_data = [["Treatment", "t-statistic", "p-value", "Significance", "Cohen's d", "Effect Size"]]
    for ps in pairwise:
        pw_data.append([
            ps["treatment"],
            str(ps["t_statistic"]),
            str(ps["p_value"]),
            ps["significance"],
            str(ps["cohens_d"]),
            ps["effect_size_label"],
        ])

    col_w = [1.1*inch, 1.0*inch, 0.85*inch, 2.1*inch, 0.85*inch, 0.85*inch]
    t = Table(pw_data, colWidths=col_w, repeatRows=1)
    t.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, 0), MID_NAVY),
        ("TEXTCOLOR",     (0, 0), (-1, 0), WHITE),
        ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, 0), 8),
        ("ALIGN",         (0, 0), (-1, -1), "CENTER"),
        ("TOPPADDING",    (0, 0), (-1, 0), 7),
        ("BOTTOMPADDING", (0, 0), (-1, 0), 7),
        ("FONTNAME",      (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE",      (0, 1), (-1, -1), 8.5),
        ("TEXTCOLOR",     (0, 1), (-1, -1), TEXT_DARK),
        ("TOPPADDING",    (0, 1), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 1), (-1, -1), 6),
        ("ROWBACKGROUNDS",(0, 1), (-1, -1), [WHITE, ROW_ALT]),
        ("LINEBELOW",     (0, 0), (-1, 0), 1.5, ACCENT_BLUE),
        ("LINEBELOW",     (0, 1), (-1, -2), 0.3, colors.HexColor("#e2e8f0")),
        ("LINEBELOW",     (0, -1), (-1, -1), 1, MID_NAVY),
        ("BOX",           (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
    ]))
    story.append(t)
    story.append(Paragraph(
        "Welch's t-test used (unequal variance assumed). Cohen's d: Small <0.5, Medium 0.5–0.8, Large >0.8.",
        caption
    ))
    story.append(Spacer(1, 10))


def create_pdf_bytes(report_text: str, structured_data: dict) -> BytesIO:
    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=0.85 * inch,
        rightMargin=0.85 * inch,
        topMargin=0.9 * inch,
        bottomMargin=0.85 * inch,
    )

    cover_title, cover_sub, cover_meta, h1, h2, body, caption, label = _styles()
    story = []

    # ── Cover page ────────────────────────────────────────────────────────────
    _cover_page(story, structured_data, cover_title, cover_sub, cover_meta)

    # ── Results tables ────────────────────────────────────────────────────────
    story.append(Paragraph("STATISTICAL RESULTS SUMMARY", label))
    story.append(HRFlowable(width="100%", thickness=1.5, color=ACCENT_BLUE, spaceAfter=12))
    _results_table(story, structured_data, h2, caption)
    _pairwise_table(story, structured_data, h2, caption)
    story.append(HRFlowable(width="100%", thickness=0.5,
                            color=colors.HexColor("#e2e8f0"), spaceAfter=16))

    # ── CSR narrative ─────────────────────────────────────────────────────────
    story.append(Paragraph("CLINICAL STUDY REPORT", label))
    story.append(HRFlowable(width="100%", thickness=1.5, color=ACCENT_BLUE, spaceAfter=14))

    for line in report_text.split("\n"):
        line = line.strip()
        if not line:
            story.append(Spacer(1, 5))
            continue

        # Markdown bold headers like **Title Page**
        if line.startswith("**") and line.endswith("**"):
            clean = line.replace("**", "")
            story.append(KeepTogether([
                Paragraph(clean, h1),
                HRFlowable(width="100%", thickness=0.5,
                           color=colors.HexColor("#dbeafe"), spaceAfter=6),
            ]))
        # Numbered section headers like "1. Title Page"
        elif len(line) > 2 and line[0].isdigit() and line[1] in (".", " "):
            parts = line.split(".", 1)
            num   = parts[0].strip()
            title = parts[1].strip() if len(parts) > 1 else line
            story.append(KeepTogether([
                Paragraph(f"<font color='#2563eb'>{num}.</font>  {title}", h1),
                HRFlowable(width="100%", thickness=0.5,
                           color=colors.HexColor("#dbeafe"), spaceAfter=6),
            ]))
        # Table-like lines (markdown pipe tables from AI output) — skip
        elif line.startswith("|"):
            continue
        else:
            story.append(Paragraph(line, body))

    doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)
    buffer.seek(0)
    return buffer