from datetime import date
import re


def create_txt_bytes(report_text: str, structured_data: dict) -> str:
    today      = date.today().strftime("%B %d, %Y")
    best_tx    = structured_data.get("best_treatment", "-")
    conf       = structured_data.get("confidence_score", "-")
    warning    = structured_data.get("warning", "-")
    conclusion = structured_data.get("conclusion", "-").upper()
    W = 100

    lines = []

    def rule(char="="):
        lines.append(char * W)

    def center(text):
        lines.append(text.center(W))

    def blank():
        lines.append("")

    # Header
    rule("=")
    blank()
    center("C L I N I C A L   S T U D Y   R E P O R T")
    blank()
    center("Generated by TrialDocAI  .  Powered by Groq LLaMA 3.3 70B")
    blank()
    center("Date: " + today + "   .   Sponsor: Demo Sponsor Inc.   .   DRAFT")
    blank()
    rule("=")
    blank()

    # Summary box
    lines.append("  SUMMARY")
    rule("-")
    col = W // 4
    lines.append(
        "  BEST TREATMENT".ljust(col) +
        "  CONCLUSION".ljust(col) +
        "  EFFECT".ljust(col) +
        "  CONFIDENCE"
    )
    lines.append(
        ("  " + str(best_tx)).ljust(col) +
        ("  " + str(conclusion)).ljust(col) +
        ("  " + str(warning)).ljust(col) +
        ("  " + str(conf))
    )
    rule("-")
    blank()

    # Results table
    results = structured_data.get("results", [])
    if results:
        lines.append("  TABLE 1. Primary Endpoint Results - Blood Pressure Reduction (mmHg)")
        rule("-")
        lines.append("  " + "Treatment".ljust(20) + "N".rjust(6) + "  " + "Mean".rjust(10) + "  " + "Std Dev".rjust(10))
        rule("-")
        for r in results:
            lines.append(
                "  " + str(r["treatment"]).ljust(20) +
                str(r["sample_size"]).rjust(6) + "  " +
                str(r["mean"]).rjust(10) + "  " +
                str(r["std_dev"]).rjust(10)
            )
        rule("-")
        lines.append("  Note: Values represent mean change from baseline +/- standard deviation.")
        blank()

    # Pairwise stats table
    pairwise = structured_data.get("pairwise_stats", [])
    if pairwise:
        lines.append("  TABLE 2. Pairwise Statistical Comparisons vs Placebo (Welch t-test)")
        rule("-")
        lines.append(
            "  " +
            "Treatment".ljust(12) +
            "t-stat".rjust(8) + "  " +
            "p-value".rjust(10) + "  " +
            "Cohens d".rjust(10) + "  " +
            "Effect".ljust(8) + "  " +
            "Significance"
        )
        rule("-")
        for ps in pairwise:
            lines.append(
                "  " +
                str(ps["treatment"]).ljust(12) +
                str(ps["t_statistic"]).rjust(8) + "  " +
                str(ps["p_value"]).rjust(10) + "  " +
                str(ps["cohens_d"]).rjust(10) + "  " +
                str(ps["effect_size_label"]).ljust(8) + "  " +
                str(ps["significance"])
            )
        rule("-")
        lines.append("  Note: Cohens d - Small <0.5, Medium 0.5-0.8, Large >0.8")
        blank()

    # CSR narrative
    rule("=")
    center("C L I N I C A L   S T U D Y   R E P O R T   -   N A R R A T I V E")
    rule("=")
    blank()

    for line in report_text.split("\n"):
        line = line.strip()

        if not line:
            blank()
            continue

        # Skip markdown pipe tables
        if line.startswith("|"):
            continue

        # Bold heading: **1. Title**
        if line.startswith("**") and line.endswith("**"):
            clean = line.replace("**", "")
            blank()
            rule("-")
            lines.append("  " + clean.upper())
            rule("-")
            blank()
            continue

        # Numbered heading: "1. Title Page"
        m = re.match(r"^(\d+)\.\s+(.+)$", line)
        if m and len(line) < 80:
            blank()
            rule("-")
            lines.append("  " + m.group(1) + ". " + m.group(2).upper())
            rule("-")
            blank()
            continue

        # Word-wrap body text
        words = line.split()
        current = "  "
        for word in words:
            if len(current) + len(word) + 1 > W - 2:
                lines.append(current)
                current = "  " + word
            else:
                if current.strip():
                    current = current + " " + word
                else:
                    current = current + word
        if current.strip():
            lines.append(current)

    blank()
    rule("=")
    center("Generated by TrialDocAI for demonstration purposes.")
    center("Not for regulatory submission without medical writer review.")
    rule("=")

    return "\n".join(lines)